-- ============================================================================
-- ADD REGENERATE THUMBNAIL STATUS
-- Migration to add 'regenerate_thumbnail' status to workflow
-- Date: 2025-11-23
-- ============================================================================
-- This migration adds the 'regenerate_thumbnail' status to the workflow
-- system. This status is used when a user rejects a generated thumbnail,
-- indicating that it needs to be regenerated by the N8N automation.
-- ============================================================================

-- Add new status to structure_allowed_status table
INSERT INTO "public"."structure_allowed_status"
  ("status_key", "status_label", "description", "workflow_phase", "sort_order", "is_active", "created_at")
VALUES
  (
    'regenerate_thumbnail',
    'Regenerate Thumbnail',
    'Indica que a thumbnail foi reprovada pelo usuário e precisa ser regerada pela automação N8N',
    'production',
    51,
    true,
    NOW()
  );

-- Add comment for documentation
COMMENT ON TABLE structure_allowed_status IS
'Workflow status definitions. The regenerate_thumbnail status (sort_order: 51) sits between
create_thumbnail (50) and create_audio_segments (60+), allowing rejected thumbnails to be
flagged for regeneration before proceeding in the production pipeline.';
