-- ============================================================================
-- ADD REGENERATE SCRIPT STATUS
-- Migration to add 'regenerate_script' status to workflow
-- Date: 2025-11-29
-- ============================================================================
-- This migration adds the 'regenerate_script' status to the workflow
-- system. This status is used when a user rejects a content package
-- (script, teaser, description), indicating that it needs to be
-- regenerated by the N8N automation.
-- ============================================================================

-- 1. Incrementar sort_order de todos os status de 8 a 23, do maior para o menor
-- para evitar conflito de unique constraint
UPDATE "public"."structure_allowed_status" SET sort_order = 24 WHERE sort_order = 23;
UPDATE "public"."structure_allowed_status" SET sort_order = 23 WHERE sort_order = 22;
UPDATE "public"."structure_allowed_status" SET sort_order = 22 WHERE sort_order = 21;
UPDATE "public"."structure_allowed_status" SET sort_order = 21 WHERE sort_order = 20;
UPDATE "public"."structure_allowed_status" SET sort_order = 20 WHERE sort_order = 19;
UPDATE "public"."structure_allowed_status" SET sort_order = 19 WHERE sort_order = 18;
UPDATE "public"."structure_allowed_status" SET sort_order = 18 WHERE sort_order = 17;
UPDATE "public"."structure_allowed_status" SET sort_order = 17 WHERE sort_order = 16;
UPDATE "public"."structure_allowed_status" SET sort_order = 16 WHERE sort_order = 15;
UPDATE "public"."structure_allowed_status" SET sort_order = 15 WHERE sort_order = 14;
UPDATE "public"."structure_allowed_status" SET sort_order = 14 WHERE sort_order = 13;
UPDATE "public"."structure_allowed_status" SET sort_order = 13 WHERE sort_order = 12;
UPDATE "public"."structure_allowed_status" SET sort_order = 12 WHERE sort_order = 11;
UPDATE "public"."structure_allowed_status" SET sort_order = 11 WHERE sort_order = 10;
UPDATE "public"."structure_allowed_status" SET sort_order = 10 WHERE sort_order = 9;
UPDATE "public"."structure_allowed_status" SET sort_order = 9 WHERE sort_order = 8;

-- 2. Inserir o novo status com sort_order = 8
INSERT INTO "public"."structure_allowed_status"
  ("status_key", "status_label", "description", "workflow_phase", "sort_order", "is_active", "created_at")
VALUES
  (
    'regenerate_script',
    'Regenerate Script',
    'Indica que o pacote de conteúdo (script, teaser, description) foi reprovado pelo usuário e precisa ser regerado pela automação N8N',
    'script',
    8,
    true,
    NOW()
  );

-- Add comment for documentation
COMMENT ON TABLE structure_allowed_status IS
'Workflow status definitions. The regenerate_script status (sort_order: 8) sits after
review_script (7), allowing rejected content packages to be flagged for regeneration
before proceeding in the production pipeline.';
